In [7]:
import copy
import numpy as np

In [8]:
def optimality_check(c):
    if [rdcd_cost for rdcd_cost in c if rdcd_cost > 1e-8]:
        return True
    else:
        return False

In [15]:
def pivoting(c,A,b,z):
    entering = (np.where(c == max(c)))[0][0]

    ratio = {row_idx:rhs/lhs[entering] for row_idx,(lhs,rhs) in enumerate(zip(A,b)) if lhs[entering] >= 0}

    min_ratio_idx = min(ratio, key=ratio.get)
    mul_val = float(1/A[min_ratio_idx][entering])

    criteria_lhs = copy.copy(A[min_ratio_idx]*mul_val)
    criteria_rhs = copy.copy(b[min_ratio_idx]*mul_val)
    
    for row_idx,(lhs,rhs) in enumerate(zip(A,b)):
        pivot_val = float(lhs[entering])
        if row_idx != min_ratio_idx:
#             if lhs[entering] > 0:
            A[row_idx] = lhs - (criteria_lhs*pivot_val)
            b[row_idx] = rhs - (criteria_rhs*pivot_val)
#             else:
#                 A[row_idx] = lhs + (criteria_lhs*pivot_val)
#                 b[row_idx] = rhs + (criteria_rhs*pivot_val)
        else:
            A[row_idx] = criteria_lhs
            b[row_idx] = criteria_rhs
    
    odj_pivot_val = c[entering]
#     if odj_pivot_val > 0:
    c -= criteria_lhs*odj_pivot_val
    z -= criteria_rhs*odj_pivot_val
#     else:
#         c += criteria_lhs*odj_pivot_val
#         z += criteria_rhs*odj_pivot_val
        
    return c,A,b,z

In [16]:
def print_tableau(step, c,A,b,z):
    print(f'===== step {step} =====')
    print(c, z)
    for lhs,rhs in zip(A,b):
        print(lhs, rhs)
    print()

In [17]:
c = np.array([2,1,1,0,0,0], dtype=np.float)
A = np.array([
    [3,1,1,1,0,0],
    [1,-1,2,0,1,0],
    [1,1,-1,0,0,1]
], dtype=np.float)
b = np.array([60,10,20], dtype=np.float)
z = 0

In [18]:
step = 1
while optimality_check(c):
    c,A,b,z = pivoting(c,A,b,z)
    
    print_tableau(step, c,A,b,z)
    
    step += 1

===== step 1 =====
[ 0.  3. -3.  0. -2.  0.] -20.0
[ 0.  4. -5.  1. -3.  0.] 30.0
[ 1. -1.  2.  0.  1.  0.] 10.0
[ 0.  2. -3.  0. -1.  1.] 10.0

===== step 2 =====
[ 0.   0.   1.5  0.  -0.5 -1.5] -35.0
[ 0.  0.  1.  1. -1. -2.] 10.0
[1.  0.  0.5 0.  0.5 0.5] 15.0
[ 0.   1.  -1.5  0.  -0.5  0.5] 5.0

===== step 3 =====
[ 0.   0.   0.  -1.5  1.   1.5] -50.0
[ 0.  0.  1.  1. -1. -2.] 10.0
[ 1.   0.   0.  -0.5  1.   1.5] 10.0
[ 0.   1.   0.   1.5 -2.  -2.5] 20.0

===== step 4 =====
[-1.  0.  0. -1.  0.  0.] -60.0
[1.33333333 0.         1.         0.33333333 0.33333333 0.        ] 23.333333333333332
[ 0.66666667  0.          0.         -0.33333333  0.66666667  1.        ] 6.666666666666666
[ 1.66666667  1.          0.          0.66666667 -0.33333333  0.        ] 36.666666666666664

